import { ContentItem } from '@/types/content';

export const MOCK_CONTENT: ContentItem[] = [
  {
    id: '1',
    type: 'movie',
    title: 'Big Buck Bunny',
    originalTitle: 'Big Buck Bunny',
    description: 'Um coelho enfrenta três esquilos travessos em uma floresta mágica. Uma animação épica da Blender Foundation.',
    longDescription: 'Big Buck Bunny conta a história de um coelho gentil e enorme que é provocado por três esquilos travessos até que decide revidar. Uma animação de curta-metragem open source criada pela Blender Foundation como showcase do Blender 3D.',
    year: 2008,
    duration: 10,
    genres: ['Animação', 'Comédia', 'Família'],
    rating: 'L',
    score: 8.2,
    popularity: 4200000,
    status: 'published',
    featured: true,
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/800px-Big_buck_bunny_poster_big.jpg',
    backdrop: 'https://peach.blender.org/wp-content/uploads/title_02_rod.jpg',
    videoSource: { provider: 'youtube', videoId: 'aqz-KE-bpKQ' },
    cast: ['Voice Cast: Blender Artists'],
    director: 'Sacha Goedegebure',
    country: 'Holanda',
    language: 'Sem diálogo',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
    tags: ['open-source', 'animação', 'blender'],
  },
  {
    id: '2',
    type: 'movie',
    title: 'Elephant Dream',
    originalTitle: 'Elephants Dream',
    description: 'Dois personagens exploram uma máquina fantástica em um mundo surrealista de engrenagens e mecanismos.',
    longDescription: 'Elephants Dream é o primeiro Open Movie produzido pela Blender Foundation. Dois personagens peculiares exploram uma máquina surreal e fantástica, revelando perspectivas completamente diferentes sobre o mesmo mundo.',
    year: 2006,
    duration: 11,
    genres: ['Animação', 'Ficção Científica', 'Arte'],
    rating: 'L',
    score: 7.5,
    popularity: 1800000,
    status: 'published',
    featured: false,
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Elephants_Dream_s5_both.jpg/800px-Elephants_Dream_s5_both.jpg',
    backdrop: 'https://upload.wikimedia.org/wikipedia/commons/7/75/Elephants_Dream_s5_both.jpg',
    videoSource: { provider: 'youtube', videoId: 'TLkA0RELQ1g' },
    cast: ['Cas Jansen', 'Tygo Gernandt'],
    director: 'Bassam Kurdali',
    country: 'Holanda',
    language: 'Inglês',
    createdAt: '2024-01-11T10:00:00Z',
    updatedAt: '2024-01-11T10:00:00Z',
    tags: ['open-source', 'surrealismo', 'blender'],
  },
  {
    id: '3',
    type: 'movie',
    title: 'Tears of Steel',
    originalTitle: 'Tears of Steel',
    description: 'Em Amsterdã, um grupo de guerreiros e cientistas tenta reverter o domínio de robôs sobre a humanidade.',
    longDescription: 'Tears of Steel é o quinto Open Movie da Blender Foundation. Combina filmagem live-action com animação CGI de alta qualidade em uma história de ficção científica sobre resistência humana contra robôs invasores.',
    year: 2012,
    duration: 12,
    genres: ['Ficção Científica', 'Ação', 'Drama'],
    rating: '12',
    score: 7.8,
    popularity: 3100000,
    status: 'published',
    featured: true,
    thumbnail: 'https://mango.blender.org/wp-content/uploads/2013/05/01_thom_celia_bridge.jpg',
    backdrop: 'https://mango.blender.org/wp-content/uploads/2013/05/01_thom_celia_bridge.jpg',
    videoSource: { provider: 'youtube', videoId: 'R6MlUcmOul8' },
    cast: ['Derek de Lint', 'Sergio Hasselbaink', 'Vanja Rukavina'],
    director: 'Ian Hubert',
    country: 'Holanda',
    language: 'Inglês',
    createdAt: '2024-01-12T10:00:00Z',
    updatedAt: '2024-01-12T10:00:00Z',
    tags: ['scifi', 'live-action', 'vfx', 'blender'],
  },
  {
    id: '4',
    type: 'movie',
    title: 'Cosmos Laundromat',
    originalTitle: 'Cosmos Laundromat',
    description: 'Uma ovelha solitária em uma ilha remota encontra um misterioso agente que lhe oferece uma segunda chance.',
    longDescription: 'Cosmos Laundromat é o décimo Open Movie da Blender Foundation. Frank, uma ovelha solitária, está prestes a desistir de tudo quando encontra Victor, um agente misterioso que lhe oferece uma jornada única.',
    year: 2015,
    duration: 13,
    genres: ['Animação', 'Fantasia', 'Comédia'],
    rating: 'L',
    score: 8.0,
    popularity: 2500000,
    status: 'published',
    featured: false,
    thumbnail: 'https://cloud.blender.org/p/cosmos-laundromat/images/Poster_A_HD.jpg',
    backdrop: 'https://cloud.blender.org/p/cosmos-laundromat/images/Poster_A_HD.jpg',
    videoSource: { provider: 'vimeo', videoId: '136272706' },
    cast: ['Animação: Blender Institute'],
    director: 'Francesco Siddi',
    country: 'Holanda',
    language: 'Inglês',
    createdAt: '2024-01-13T10:00:00Z',
    updatedAt: '2024-01-13T10:00:00Z',
    tags: ['sheep', 'surreal', 'blender', 'fantasy'],
  },
  {
    id: '5',
    type: 'movie',
    title: 'Glass Half',
    originalTitle: 'Glass Half',
    description: 'Um curta-metragem lírico sobre perspectivas e como enxergamos o mundo ao nosso redor.',
    longDescription: 'Um filme experimental que explora a dualidade das perspectivas humanas através de imagens poéticas e música cuidadosamente composta.',
    year: 2020,
    duration: 8,
    genres: ['Documentário', 'Arte', 'Experimental'],
    rating: 'L',
    score: 7.2,
    popularity: 450000,
    status: 'published',
    featured: false,
    thumbnail: 'https://i.vimeocdn.com/video/931164078-d16a2ba7c70e8acf0d23fe0e78aa78a5d0f7e47d5fc75c0e4d24d39efcad7e7e_1280',
    backdrop: 'https://i.vimeocdn.com/video/931164078-d16a2ba7c70e8acf0d23fe0e78aa78a5d0f7e47d5fc75c0e4d24d39efcad7e7e_1280',
    videoSource: { provider: 'vimeo', videoId: '76979871' },
    cast: ['Elenco desconhecido'],
    country: 'Internacional',
    language: 'Sem diálogo',
    createdAt: '2024-01-14T10:00:00Z',
    updatedAt: '2024-01-14T10:00:00Z',
    tags: ['experimental', 'poético', 'curta'],
  },
  {
    id: '6',
    type: 'movie',
    title: 'Caminhos da Natureza',
    originalTitle: 'Paths of Nature',
    description: 'Uma jornada visual impressionante pelos ecossistemas mais remotos do planeta.',
    longDescription: 'Uma produção documental que leva o espectador a uma viagem inesquecível pelos biomas mais intocados da Terra, mostrando a beleza e fragilidade da natureza selvagem.',
    year: 2019,
    duration: 45,
    genres: ['Documentário', 'Natureza'],
    rating: 'L',
    score: 8.7,
    popularity: 2200000,
    status: 'published',
    featured: true,
    thumbnail: 'https://i.vimeocdn.com/video/601064198-beedd97fb2f9e218c0e84e0a0c56c89ed5de87d46d4df26f24eed5ae1d7fb9c4_1280',
    backdrop: 'https://i.vimeocdn.com/video/601064198-beedd97fb2f9e218c0e84e0a0c56c89ed5de87d46d4df26f24eed5ae1d7fb9c4_1280',
    videoSource: { provider: 'vimeo', videoId: '45370926' },
    cast: ['Narração: Nature Films'],
    director: 'Nature Studios',
    country: 'Internacional',
    language: 'Inglês',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    tags: ['natureza', 'vida selvagem', 'documentário'],
  },
  {
    id: '7',
    type: 'series',
    title: 'Blender Chronicles',
    description: 'Uma série documental explorando os bastidores da criação de animações 3D profissionais.',
    year: 2022,
    seasons: 2,
    totalEpisodes: 12,
    genres: ['Documentário', 'Tecnologia', 'Arte'],
    rating: 'L',
    score: 8.4,
    popularity: 1600000,
    status: 'published',
    featured: false,
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Blender_logo_no_text.svg/1200px-Blender_logo_no_text.svg.png',
    backdrop: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/1200px-Big_buck_bunny_poster_big.jpg',
    cast: ['Ton Roosendaal', 'Blender Community'],
    country: 'Internacional',
    language: 'Inglês',
    createdAt: '2024-01-16T10:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
    tags: ['blender', '3d', 'making-of'],
  },
  {
    id: '8',
    type: 'movie',
    title: 'Agent 327',
    originalTitle: 'Agent 327: Operation Barbershop',
    description: 'O famoso agente secreto holandês enfrenta uma missão perigosa em uma barbearia suspeita.',
    longDescription: 'Baseado no personagem de Martin Lodewijk, Agent 327 é um curta-metragem de ação da Blender Institute que mostra o agente secreto mais stylish da Holanda em uma ação alucinante.',
    year: 2017,
    duration: 3,
    genres: ['Animação', 'Ação', 'Comédia'],
    rating: '12',
    score: 8.6,
    popularity: 5800000,
    status: 'published',
    featured: true,
    thumbnail: 'https://agent327.com/wp-content/uploads/2017/05/A327_KeyArt_v08.jpg',
    backdrop: 'https://agent327.com/wp-content/uploads/2017/05/A327_KeyArt_v08.jpg',
    videoSource: { provider: 'youtube', videoId: 'mN0zPOpADL4' },
    cast: ['Animação: Blender Institute'],
    director: 'Hjalti Hjalmarsson',
    country: 'Holanda',
    language: 'Sem diálogo',
    createdAt: '2024-01-17T10:00:00Z',
    updatedAt: '2024-01-17T10:00:00Z',
    tags: ['ação', 'espião', 'blender', 'stylish'],
  },
  {
    id: '9',
    type: 'movie',
    title: 'Sprite Fright',
    originalTitle: 'Sprite Fright',
    description: 'Um grupo de adolescentes invade uma floresta encantada e encontra criaturas que não gostam de intrusos.',
    year: 2021,
    duration: 8,
    genres: ['Animação', 'Terror', 'Comédia'],
    rating: '12',
    score: 8.3,
    popularity: 3400000,
    status: 'published',
    featured: false,
    thumbnail: 'https://www.blender.org/wp-content/uploads/2021/10/sprite-fright-poster.jpg',
    backdrop: 'https://www.blender.org/wp-content/uploads/2021/10/sprite-fright-poster.jpg',
    videoSource: { provider: 'youtube', videoId: 'jn-xbSQGPkc' },
    cast: ['Animação: Blender Studio'],
    director: 'Mathieu Auvray',
    country: 'Holanda',
    language: 'Inglês',
    createdAt: '2024-01-18T10:00:00Z',
    updatedAt: '2024-01-18T10:00:00Z',
    tags: ['terror', 'fantasia', 'blender', 'sprites'],
  },
  {
    id: '10',
    type: 'movie',
    title: 'Wing It!',
    originalTitle: 'Wing It!',
    description: 'Dois pombos aventureiros tentam aprender a voar de maneiras cada vez mais criativas e desastrosas.',
    year: 2022,
    duration: 5,
    genres: ['Animação', 'Comédia', 'Família'],
    rating: 'L',
    score: 7.6,
    popularity: 980000,
    status: 'draft',
    featured: false,
    thumbnail: 'https://www.blender.org/wp-content/uploads/2022/01/CapaWingIt.jpg',
    backdrop: 'https://www.blender.org/wp-content/uploads/2022/01/CapaWingIt.jpg',
    videoSource: { provider: 'youtube', videoId: 'WhWc3b3KhnY' },
    cast: ['Animação: Blender Studio'],
    country: 'Holanda',
    language: 'Sem diálogo',
    createdAt: '2024-01-19T10:00:00Z',
    updatedAt: '2024-01-19T10:00:00Z',
    tags: ['pombos', 'comédia', 'blender'],
  },
  {
    id: '11',
    type: 'movie',
    title: 'Coffee Run',
    originalTitle: 'Coffee Run',
    description: 'Uma personagem em busca do café perfeito percorre uma cidade que vai se transformando ao redor dela.',
    year: 2020,
    duration: 3,
    genres: ['Animação', 'Aventura'],
    rating: 'L',
    score: 7.9,
    popularity: 1200000,
    status: 'published',
    featured: false,
    thumbnail: 'https://www.blender.org/wp-content/uploads/2020/04/BlenderOpenMovieCoffeeRun_Poster_v2.jpg',
    backdrop: 'https://www.blender.org/wp-content/uploads/2020/04/BlenderOpenMovieCoffeeRun_Poster_v2.jpg',
    videoSource: { provider: 'youtube', videoId: 'TLkA0RELQ1g' },
    cast: ['Animação: Blender Studio'],
    director: 'Hjalti Hjalmarsson',
    country: 'Holanda',
    language: 'Sem diálogo',
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
    tags: ['café', 'cidade', 'corrida'],
  },
  {
    id: '12',
    type: 'series',
    title: 'Open Source Stories',
    description: 'Histórias inspiradoras de criadores ao redor do mundo que usam software livre para realizar seus sonhos.',
    year: 2023,
    seasons: 1,
    totalEpisodes: 8,
    genres: ['Documentário', 'Tecnologia', 'Inspiração'],
    rating: 'L',
    score: 8.1,
    popularity: 780000,
    status: 'published',
    featured: false,
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Blender_logo_no_text.svg/1200px-Blender_logo_no_text.svg.png',
    backdrop: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/1200px-Big_buck_bunny_poster_big.jpg',
    cast: ['Vários criadores'],
    country: 'Internacional',
    language: 'Multilíngue',
    createdAt: '2024-01-21T10:00:00Z',
    updatedAt: '2024-01-21T10:00:00Z',
    tags: ['open-source', 'criadores', 'inspiração'],
  },
];

export const GENRES = ['Animação', 'Ação', 'Aventura', 'Arte', 'Comédia', 'Drama', 'Documentário', 'Experimental', 'Família', 'Fantasia', 'Ficção Científica', 'Natureza', 'Tecnologia', 'Terror'];
export const RATINGS = ['L', '10', '12', '14', '16', '18'];
export const COUNTRIES = ['Holanda', 'Brasil', 'EUA', 'Internacional', 'França', 'Alemanha'];
export const LANGUAGES = ['Português', 'Inglês', 'Sem diálogo', 'Multilíngue', 'Espanhol'];
